services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8765:8765"
  ui:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - backend
