/**
 * Hand-maintained types for gaps in the generated OpenAPI client.
 *
 * src/client/ is fully regenerated by `npm run generate:client` and wiped on
 * every run — anything hand-written there gets silently deleted. This file
 * is the home for small patches that used to live inside src/client/models/
 * by mistake.
 */

/** additional_claims is an inline `additionalProperties` object in the spec,
 * so openapi-typescript-codegen doesn't emit a named model for it. */
export type TrustMarkSpecAdditionalClaims = Record<string, unknown>;
